### ISSUE TITLE
Licensing for commercial

### ISSUE THREAD

**Issue by dmkirichen** [RenarsKokins/ScoreboardOCR#1]
Hi, I would like to use your project to help my friend (video operator) with his sport translations.
But I am not sure If I can do this since you don't have LICENSE file.

So my question is do you give a permission to use this for commercial projects?

**Comment by RenarsKokins** [comment]
Hello @dmkirichen 

Yes, I give permission to use this project for commercial purposes. I will add licence pretty soon.

**Comment by RenarsKokins** [comment]
License has been added, enjoy!
