### ISSUE TITLE
Crashing on choosing device

### ISSUE THREAD

**Issue by dmkirichen** [RenarsKokins/ScoreboardOCR#2]
Hi, thanks for quick reply on LICENSE issue, that was really fast

I am working on Windows 10 x64
I finally managed to build the project and now I am crashing on choosing capture device.
I tried to look for some log files or something, but, honestly, I don't have much experience with C++, so I might have missed something.

Here is output of the program (I used my android smartphone as video device using DroidCam):
```
20:13:50: Starting C:\Code\ScoreboardOCR\scoreboardocr\build\Desktop_Qt_6_7_1_MinGW_64_bit-Debug\debug\scoreboardocr.exe...
Initializing filter manager...
Initiating caputure manager...
Initializing recognition manager...
Initializing capture scene...
Initializing capture scene...
Initializing capture scene...
Initializing main worker...
Initializing settings manager...
Loaded svm: "C:/Code/ScoreboardOCR/scoreboardocr/SVMs/7segment.svm"
SVM var count: 256
Found device: "\\\\?\\root#media#0001#{e5323777-f976-4f5b-9b55-b94699c46e44}\\global" | "DroidCam Source 3"
Found device: "\\\\?\\root#media#0001#{e5323777-f976-4f5b-9b55-b94699c46e44}\\global" | "DroidCam Source 3"
20:13:59: C:\Code\ScoreboardOCR\scoreboardocr\build\Desktop_Qt_6_7_1_MinGW_64_bit-Debug\debug\scoreboardocr.exe crashed.

```
![изображение](https://github.com/RenarsKokins/ScoreboardOCR/assets/31488829/39a3ec5c-3364-4614-88a1-c130bca01d55)
![изображение](https://github.com/RenarsKokins/ScoreboardOCR/assets/31488829/925d0fd0-4be5-4fae-a179-c1819dfd9d17)
When I press "Start Capture" everything crashes

So yeah, the main question for now is do you have logs generated somewhere? 
If not then second question is how can I possibly debug this behaviour?

**Comment by RenarsKokins** [comment]
Hello @dmkirichen 

Sorry for late response, had other things to do. 
About logging - only way to get more logs is to add two OpenCV environment variables to the build:
```
OPENCV_LOG_LEVEL=DEBUG
OPENCV_VIDEOIO_DEBUG=1
```
This would enable logging for OpenCV, but there are no additional logs that you can enable in this project :)

I checked out this problem on my PC on several cameras and either the cameras worked or a appropriate error message was shown. Then I tried DroidCam and I could get the program to crash. Seems that OpenCV has a hard time with DroidCam client (PC), as it is what makes the program crash (in capturemanager.cpp->CaptureManager::initUSBCapture() you can add breakpoint to the code, where video capture is initiated to check this problem out).

I tried to fix this problem somehow (for openCV), but could not do it properly, maybe you can try to find a solution if you want :)

Anyways, I saw that DroidCam offered a possibilty to view video through IP, so I added IP camera support. That means that you can go to capture tab->IP capture and enter IP address of your camera (for example: http://192.168.1.102:4747/video , check DroidCam for this IP cam access), then press "start capture" and it should start working. Tried it with my phone and video was caputred and displayed in ScoreboardOCR.

If any more questions, feel free to ask :)

If not, you can close this issue.

**Comment by dmkirichen** [comment]
Thanks, that is helpful feature since most of the sport operators use ip connections with cameras
I've managed to connect to DroidCam that way, so the issue can be closed
